language: java

env:
  - MILL_VERSION=0.3.6

before_script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION} && chmod +x ~/bin/mill

script:
  - mill -i site.jbake

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local-dir: out/site/jbake/dest
  name: Tobias Roeser (Bot)
  email: le.petit.fou@web.de
  on:
    branch: site
